/**
 * Autogenerated by Thrift Compiler (0.9.2)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.cimbel.ircservice;


public enum MessageErrorType implements org.apache.thrift.TEnum {
    USER_ID_NOT_FOUND(0),
    CHANNEL_NOT_FOUND(1),
    NOT_CHANNEL_MEMBER(2),
    UNKNOWN_FAILURE(3);

    private final int value;

    MessageErrorType(int value) {
        this.value = value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     *
     * @return null if the value is not found.
     */
    public static MessageErrorType findByValue(int value) {
        switch (value) {
            case 0:
                return USER_ID_NOT_FOUND;
            case 1:
                return CHANNEL_NOT_FOUND;
            case 2:
                return NOT_CHANNEL_MEMBER;
            case 3:
                return UNKNOWN_FAILURE;
            default:
                return null;
        }
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }
}
