/**
 * Autogenerated by Thrift Compiler (0.9.2)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.cimbel.ircservice;


public enum UserManagementErrorType implements org.apache.thrift.TEnum {
    NICKNAME_USED(0),
    USER_ID_NOT_FOUND(1),
    CHANNEL_NOT_FOUND(2);

    private final int value;

    UserManagementErrorType(int value) {
        this.value = value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     *
     * @return null if the value is not found.
     */
    public static UserManagementErrorType findByValue(int value) {
        switch (value) {
            case 0:
                return NICKNAME_USED;
            case 1:
                return USER_ID_NOT_FOUND;
            case 2:
                return CHANNEL_NOT_FOUND;
            default:
                return null;
        }
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }
}
